spring:
  config:
    import: "optional:file:./.env[.properties]"

  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

projectflow:
  ai:
    provider: stub
    stub:
      pre-check-scenario: no-problems
      generation-scenario: with-dates
