spring:
  application:
    name: ProjectFlow

  profiles:
    default: dev

  jpa:
    open-in-view: false

server:
  servlet:
    session:
      timeout: 60m
      cookie:
        http-only: true
        same-site: lax
        secure: false
