ALTER TABLE ai_plan_generation_workflows DROP CONSTRAINT ck_ai_workflows_status;

UPDATE ai_plan_generation_workflows
SET status = 'PRE_CHECK_COMPLETED'
WHERE status = 'PRE_CHECK_SUCCEEDED';

ALTER TABLE ai_plan_generation_workflows ADD CONSTRAINT ck_ai_workflows_status CHECK (status IN (
    'PRE_CHECK_PENDING', 'PRE_CHECK_RUNNING', 'PRE_CHECK_RETRY_PENDING',
    'PRE_CHECK_COMPLETED', 'PRE_CHECK_NEEDS_REVIEW', 'PRE_CHECK_CANCELLED',
    'GENERATION_PENDING', 'GENERATION_RUNNING', 'GENERATION_CANCELLED',
    'ASSUMPTIONS_REVIEW_PENDING', 'GENERATION_COMPLETED', 'GENERATION_FAILED',
    'TECHNICAL_FAILURE'));
