-- Existing projects created before subcategory selection became mandatory are
-- assigned to the matching explicit "Sonstiges" option.
UPDATE projects
SET subcategory = CASE category
    WHEN 'EDUCATION' THEN 'OTHER_EDUCATION'
    WHEN 'SOFTWARE_TECHNOLOGY' THEN 'OTHER_SOFTWARE_AND_TECHNOLOGY'
    WHEN 'EVENT' THEN 'OTHER_EVENT'
    WHEN 'HOME' THEN 'OTHER_HOME'
    WHEN 'CREATIVE' THEN 'OTHER_CREATIVE_PROJECT'
    WHEN 'CAREER' THEN 'OTHER_CAREER'
    WHEN 'HEALTH_PERSONAL_DEVELOPMENT' THEN 'OTHER_HEALTH_AND_PERSONAL_DEVELOPMENT'
    WHEN 'TRAVEL' THEN 'OTHER_TRAVEL'
END
WHERE subcategory IS NULL
  AND category <> 'OTHER';

UPDATE plan_templates
SET subcategory = CASE category
    WHEN 'EDUCATION' THEN 'OTHER_EDUCATION'
    WHEN 'SOFTWARE_TECHNOLOGY' THEN 'OTHER_SOFTWARE_AND_TECHNOLOGY'
    WHEN 'EVENT' THEN 'OTHER_EVENT'
    WHEN 'HOME' THEN 'OTHER_HOME'
    WHEN 'CREATIVE' THEN 'OTHER_CREATIVE_PROJECT'
    WHEN 'CAREER' THEN 'OTHER_CAREER'
    WHEN 'HEALTH_PERSONAL_DEVELOPMENT' THEN 'OTHER_HEALTH_AND_PERSONAL_DEVELOPMENT'
    WHEN 'TRAVEL' THEN 'OTHER_TRAVEL'
END
WHERE subcategory IS NULL
  AND category IS NOT NULL
  AND category <> 'OTHER';
